### PR TITLE
better outer boundary condition for γ-modes

### PR DESCRIPTION
**Pull request by darthoctopus**
After implementing my own pulsation solver in the natural buoyancy coordinate, I've come to understand that the previously described behaviour of obtaining an incorrect number of nodes is not a property of the coordinate singularity at the outer turning point per se, but rather a consequence of an incorrect choice of outer boundary condition. It turns out that the correct generalisation from the Cowling approximation is to set the derivative of the gravitational perturbation to zero at both the origin (already done previously), but also  at the outer boundary. This produces the correct number of nodes, with the desired quasisinusoidal behaviour when plotted in terms of the natural quantities ψ and f_l (see plot). The coordinate singularity means that the eigenfunctions are nondifferentiable with respect to f_l at the outer boundary.

gyre

### CODE REVIEW

**Comment by darthoctopus** [comment]
Note that this does not completely fix the boundary issues; in particular the coordinate singularity still results in incorrect computation of y_2 and y_3 as compared to when shooting in buoyancy coordinates. This can be alleviated by truncating the model manually, but that seems like a less than ideal solution.

**Comment by rhdtownsend** [comment]
Can you provide guidelines on when a user might want to use GAMMA1 vs GAMMA2?

**Comment by darthoctopus** [comment]
I'm still trying to figure this out, but it seems like GAMMA1 yields eigenfunctions consistent with the full oscillation equations when there's no outer convection zone (e.g. fully radiative polytrope), and GAMMA2 yields eigenfunctions that look like those of mixed modes (see plot). I'm still not 100% sure it's correct, though…
comparison

**Comment by darthoctopus** [comment]
At this point I am convinced that the GAMMA1 boundary condition is valid, and I've spent some time seeing how the GAMMA2 boundary condition behaves over a range of evolutionary phases. After some experimentation, I think I am satisfied with its behaviour. Unlike the previous GAMMA boundary condition, it suppresses f-mode-like solutions with no roots in the interior, which I think is desirable: the f-mode-like solutions that would arise with the old GAMMA boundary condition, and with other boundary conditions like JCD, don't appear to be physical (in that they don't correspond to anything returned from solutions to the full oscillation equations). I have been able to get good numerical agreement between the matrix eigenvalues derived from integrals of the form of Ong & Basu 2020 computed with respect to the GAMMA2 boundary condition, and the BVP eigenvalues obtained directly from GYRE.

Because of this, even if it's not entirely correct, I think the current GAMMA2 BC is useful enough to be merged, although I think I want to get your opinion on this (both re: correctness and re: utility). If you agree, I will tidy up the pull request to update the test cases.

**Comment by rhdtownsend** [comment]
Joel -- I've merged this commit, but now the tests fail on rgb-isolate-gamma. It seems the GAMMA outer boundary condition needs to be updated to one of GAMMA1 or GAMMA2 -- which should I choose?

**Pull request merged**
